# Introduction to classes

### Exercise 2

In [619]:
print(type([1, 2]))

print(type((1, 2)))

print(type({'a':1, 'b':2}))

<class 'list'>
<class 'tuple'>
<class 'dict'>


### Exercise 3

In [620]:
list1 = [1, 2, 3, 4, 5]

list2 = [6, 7, 8, 9, 10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [621]:
#The operation + applied to lists agregates one after the other

### Exercise 4

In [622]:
list3 = list1

list1[0] = 2

print(list1, list3)

[2, 2, 3, 4, 5] [2, 2, 3, 4, 5]


In [623]:
#The assigment = changes an element on the list. Note that list3 is not
#a new object, but another name of list1. We can create another list
#with the constructor list().

In [624]:
list4 = list(list2)

list2[0], list2[1] = 5, 8

print(list2, list4)

[5, 8, 8, 9, 10] [6, 7, 8, 9, 10]


In [625]:
#Now list 4 remains unchanged

# Classes

### Exercise 1

In [1]:
import math

class Complex:
    """ Complex number with module and phase as attributes
    """
        
    def __init__(self, mod, phase):
        """ To construct a complex number from the module and the phase
        """
        if (mod < 0): 
            raise TypeError('module must be zero or positive')
        self.mod   = mod
        self.phase = phase
        return
    
    def real(self):
        """ return the real part
        """
        real = self.mod * math.cos(self.phase) 
        return real
 
    def img(self):
        """ return the imaginary part
        """
        img = self.mod * math.sin(self.phase)
        return img
    
    def __abs__(self):
        """ return the module
        """
        return self.mod
    
    def __add__(self, y):
        """ add to complex numbers <=> x+y
        """
        real = self.real() + y.real()
        img  = self.img()  + y.img()
        mod  = math.sqrt(real*real + img*img)
        phase = 0.
        if (mod > 0): 
            phase = math.acos(real / mod)
        return Complex(mod, phase)
    
    def __prod__(self, y):
        """ the product of two complex numbers: x*y
        """ 
        mod   = self.mod   * y.mod
        phase = self.phase + y.phase
        return Complex(mod, phase)
        
    def conjugate(self):
        """ complex conjugate
        """
        return Complex(self.mod, -1. * self.phase)
    
    def __str__(self):
        """ convert to a string
        """
        s = str(self.mod)+'e^'+str(self.phase)
        return s

### Vector Class

In [2]:
import math

import numpy as np

class Vector3D:
    
    def __init__(self, x, y, z):
        """ constructor of a Vector3D. Inputs: x, y, z coordinates
        """
        self.x = x
        self.y = y
        self.z = z
        return
    
    def __str__(self):
        """ convert a Vector3D to a string
        """
        ss = '(' + str(self.x) + ',' + str(self.y) + ',' + str(self.z) + ')'
        return ss
    
    def __add__(self, b):
        """ add two Vector3D
        """
        x = self.x + b.x
        y = self.y + b.y
        z = self.z + b.z
        return Vector3D(x, y, z)
    
    def __mul__(self, value):
        """ multiplies the Vector3D times the value if integer or float. Scalar product if value is an array or list
        """
        if type(value) == int or type(value) == float:
            x = self.x * value
            y = self.y * value
            z = self.z * value
            return Vector3D(x, y, z)
        
        if type(value) == list or type(value) == np.ndarray:
            x = self.x * value[0]
            y = self.y * value[1]
            z = self.z * value[2]
            return Vector3D(x, y, z)
        
    def __rmul__(self, value):
        """ multiplies the value times the Vector3D if integer or float. Scalar product if value is an array or list
        """
        return Vector3D.__mul__(self, value)
    
    def cross(self, vector):
        """ performs the vectorial product of Vector3D times vector
        """
        x = self.y * vector[2] - self.z * vector[1]
        y = self.z * vector[0] - self.x * vector[2]
        z = self.x * vector[1] - self.y * vector[0]
        return Vector3D(x, y, z)
    
    def __abs(self):
        """ calculates the module of the Vector3D
        """
        return math.sqrt(self * self)
    
    def __eq__(self, b):
        assert isinstance(b, Vector3D)
        return self.x == b

In [3]:
class Vector:
    
    def __init__(self, a):
        """ constructor of a Vector. Input : list or numpy.ndarray
        """
        assert isinstance(a, list) or isinstance(a, tuple) or isinstance(a, Vector), 'Wrong input, insert a list or numpy.ndarray'
        self.a = list(a)
        return
            
    def __getitem__(self, i):
        """ get the i element of the Vector
        """
        return self.a[i]
    
    def __setitem__(self, i, xi):
        """ set the i element to the value xi
        """
        return self.a[i] == xi
    
    def __len__(self):
        """ length of the Vector
        """
        return len(self.a)
    
    def __add__(self, x):
        """ add Vector + x
        """
        return Vector([self[i] + x[i] for i in range(len(self))])
    
    def __radd__(self, x):
        """ add x + Vector
        """
        return Vector.__add__(self, x)
    
    def __mul__(self, x):
        """ multiply Vector times x
        """
        if isinstance(x, float) or isinstance(x, int) or isinstance(x, complex):
            return Vector([self[i] * x for i in range(len(self))])
        
        if isinstance(x, np.ndarray) or isinstance(x, list) or isinstance(x, Vector):
            return Vector([self[i] * x[i] for i in range(len(self))])
        
    def __rmul__(self, x):
        """ multiply x times Vector
        """
        return Vector.__mul__(self, x)
    
    def __abs__(self):
        """ calculate the module of the Vector
        """
        return np.sqrt(self * self)
    
    def __eq__(self, x):
        """ sets x equal to self
        """
        assert isinstance(x, Vector) or isinstance(x, list) or isinstance(x, np.ndarray), 'Type not possible for equality'
        return self.a == [x[i] for i in range(len(self))]
    
    def __float__(self):
        """ convert elements of Vector into floats
        """
        return Vector([np.float(self[i]) for i in range(len(self))])

### Matrix class

In [4]:
class Matrix:
    
    def __init__(self, values, rows, columns):
        """ constructor of Matrix.
        """
        self.rows = rows
        self.columns = columns
        self.a = list(values)
        
        assert isinstance(values, Vector) or isinstance(values, np.ndarray) or\
        isinstance(values, list), 'Type not understood'
        
        if type(values) == 'Vector' or type(values) == np.ndarray:
            
            matrix = np.vstack((np.split(values, rows)))
        
            self.values = np.array(matrix)
        
        return
    
        if type(values) == list:

            values_a = np.array([])

            for i in values: values_a = np.append(values_a, i)

            matrix = np.vstack((np.split(values, rows))) 
            
            self.values = np.array(matrix)
        
        return
    
    
    def __getitem__(self, i):
        """ get the [i, j] element of the Matrix
        """
        return self.values[i] 
    
    
    def __setitem__(self, i, value):
        """ set [i, j] element to value
        """
        self.values[i] = value
        return
    
    
    def __add__(self, value):
        """ add self + value
        """
        if type(value) == int or type(value) == float or type(value) == complex:
            
            return Matrix([self.a[i] + value for i in range(len(self.a))], self.rows, self.columns)
    
        if type(value) == Matrix:
            
            c = [self.a[i] + value.a[i] for i in range(len(self.a))]
            
        return Matrix(c, self.rows, self.columns)
                 
    
    def shape(self):
        """ shape Matrix
        """
        return self.rows, self.columns

In [5]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

b = np.array([])

for i in a : b = np.append(b, np.array([i]))

print(len(b))

15


In [6]:
c = Matrix(b, 3, 5)

print(c.values)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


In [9]:
h = c + 5

print(type(c), type(h))

print (h.values)

<class '__main__.Matrix'> <class '__main__.Matrix'>


AttributeError: 'Matrix' object has no attribute 'values'

In [8]:
d = b * 5

e = Matrix(d, 3, 5)

print(e.a)

print(type(e))

[5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 35.0, 40.0, 45.0, 50.0, 55.0, 60.0, 65.0, 70.0, 75.0]
<class '__main__.Matrix'>


In [606]:
f = c + e

print(f.values)

print(Matrix.shape(f))

#print(e.a, c.a)

AttributeError: 'Matrix' object has no attribute 'values'